services:

  # MongoDB
  # --------------------------------------------------------------------------------
  # Used by event store and read store for managing and reading application data. 

  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./.volumes/mongo/local:/data/db
    networks:
      - localdev

  # Cerbos
  # --------------------------------------------------------------------------------
  # Policy engine for application access control.

  cerbos:
    container_name: cerbos
    image: ghcr.io/cerbos/cerbos:latest
    command: ["server", "--config=/config.yaml"]
    ports:
      - "3592:3592"
      - "3593:3593"
      - "3594:3594"
    volumes:
      - ./cerbos.yaml:/config.yaml
      - ./modules/identity/cerbos/policies:/data/policies/identity
      - ./modules/workspace/cerbos/policies:/data/policies/workspace
    networks:
      - localdev

networks:
  localdev:
    driver: bridge
